language: node_js

sudo: true

node_js:
  - 14.17.0

script:
  npm test

addons:
  chrome: stable

branches:
  only:
    - master

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull eclipse-mosquitto

before_script:
  - docker run -d -p 9001:9001 -v $(pwd)/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro eclipse-mosquitto
